//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteNumerosAleatorios.ServiceNumerosAleatorios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNumerosAleatorios.IWCFNumeroAleatorios")]
    public interface IWCFNumeroAleatorios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFNumeroAleatorios/GetListaNumeros", ReplyAction="http://tempuri.org/IWCFNumeroAleatorios/GetListaNumerosResponse")]
        int[] GetListaNumeros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFNumeroAleatorios/GetListaNumeros", ReplyAction="http://tempuri.org/IWCFNumeroAleatorios/GetListaNumerosResponse")]
        System.Threading.Tasks.Task<int[]> GetListaNumerosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFNumeroAleatoriosChannel : ClienteNumerosAleatorios.ServiceNumerosAleatorios.IWCFNumeroAleatorios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFNumeroAleatoriosClient : System.ServiceModel.ClientBase<ClienteNumerosAleatorios.ServiceNumerosAleatorios.IWCFNumeroAleatorios>, ClienteNumerosAleatorios.ServiceNumerosAleatorios.IWCFNumeroAleatorios {
        
        public WCFNumeroAleatoriosClient() {
        }
        
        public WCFNumeroAleatoriosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFNumeroAleatoriosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFNumeroAleatoriosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFNumeroAleatoriosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetListaNumeros() {
            return base.Channel.GetListaNumeros();
        }
        
        public System.Threading.Tasks.Task<int[]> GetListaNumerosAsync() {
            return base.Channel.GetListaNumerosAsync();
        }
    }
}
