//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCollatz.ServicioCollatz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCollatz.ICollatz")]
    public interface ICollatz {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollatz/ConjeturaCollatz", ReplyAction="http://tempuri.org/ICollatz/ConjeturaCollatzResponse")]
        int[] ConjeturaCollatz(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollatz/ConjeturaCollatz", ReplyAction="http://tempuri.org/ICollatz/ConjeturaCollatzResponse")]
        System.Threading.Tasks.Task<int[]> ConjeturaCollatzAsync(int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICollatzChannel : ClienteCollatz.ServicioCollatz.ICollatz, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CollatzClient : System.ServiceModel.ClientBase<ClienteCollatz.ServicioCollatz.ICollatz>, ClienteCollatz.ServicioCollatz.ICollatz {
        
        public CollatzClient() {
        }
        
        public CollatzClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CollatzClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollatzClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollatzClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] ConjeturaCollatz(int numero) {
            return base.Channel.ConjeturaCollatz(numero);
        }
        
        public System.Threading.Tasks.Task<int[]> ConjeturaCollatzAsync(int numero) {
            return base.Channel.ConjeturaCollatzAsync(numero);
        }
    }
}
