//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IContratoCalculadora")]
    public interface IContratoCalculadora {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoCalculadora/suma", ReplyAction="http://tempuri.org/IContratoCalculadora/sumaResponse")]
        int suma(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoCalculadora/suma", ReplyAction="http://tempuri.org/IContratoCalculadora/sumaResponse")]
        System.Threading.Tasks.Task<int> sumaAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoCalculadora/Multiplicar", ReplyAction="http://tempuri.org/IContratoCalculadora/MultiplicarResponse")]
        int Multiplicar(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoCalculadora/Multiplicar", ReplyAction="http://tempuri.org/IContratoCalculadora/MultiplicarResponse")]
        System.Threading.Tasks.Task<int> MultiplicarAsync(int num1, int num2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContratoCalculadoraChannel : Calculadora1.ServiceReference1.IContratoCalculadora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContratoCalculadoraClient : System.ServiceModel.ClientBase<Calculadora1.ServiceReference1.IContratoCalculadora>, Calculadora1.ServiceReference1.IContratoCalculadora {
        
        public ContratoCalculadoraClient() {
        }
        
        public ContratoCalculadoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContratoCalculadoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratoCalculadoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratoCalculadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int suma(int num1, int num2) {
            return base.Channel.suma(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> sumaAsync(int num1, int num2) {
            return base.Channel.sumaAsync(num1, num2);
        }
        
        public int Multiplicar(int num1, int num2) {
            return base.Channel.Multiplicar(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicarAsync(int num1, int num2) {
            return base.Channel.MultiplicarAsync(num1, num2);
        }
    }
}
