//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteDepartamentos.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departamentos", Namespace="http://schemas.datacontract.org/2004/07/LogicaDepartamento.Models")]
    [System.SerializableAttribute()]
    public partial class Departamentos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad {
            get {
                return this.LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadField, value) != true)) {
                    this.LocalidadField = value;
                    this.RaisePropertyChanged("Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceDepartamentos")]
    public interface IServiceDepartamentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDepartamentos/GetDepartamentos", ReplyAction="http://tempuri.org/IServiceDepartamentos/GetDepartamentosResponse")]
        ClienteDepartamentos.ServiceReference1.Departamentos[] GetDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDepartamentos/GetDepartamentos", ReplyAction="http://tempuri.org/IServiceDepartamentos/GetDepartamentosResponse")]
        System.Threading.Tasks.Task<ClienteDepartamentos.ServiceReference1.Departamentos[]> GetDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDepartamentos/GetDepartamentosAsynca", ReplyAction="http://tempuri.org/IServiceDepartamentos/GetDepartamentosAsyncaResponse")]
        ClienteDepartamentos.ServiceReference1.Departamentos[] GetDepartamentosAsynca();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDepartamentos/GetDepartamentosAsynca", ReplyAction="http://tempuri.org/IServiceDepartamentos/GetDepartamentosAsyncaResponse")]
        System.Threading.Tasks.Task<ClienteDepartamentos.ServiceReference1.Departamentos[]> GetDepartamentosAsyncaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDepartamentosChannel : ClienteDepartamentos.ServiceReference1.IServiceDepartamentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDepartamentosClient : System.ServiceModel.ClientBase<ClienteDepartamentos.ServiceReference1.IServiceDepartamentos>, ClienteDepartamentos.ServiceReference1.IServiceDepartamentos {
        
        public ServiceDepartamentosClient() {
        }
        
        public ServiceDepartamentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDepartamentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDepartamentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDepartamentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteDepartamentos.ServiceReference1.Departamentos[] GetDepartamentos() {
            return base.Channel.GetDepartamentos();
        }
        
        public System.Threading.Tasks.Task<ClienteDepartamentos.ServiceReference1.Departamentos[]> GetDepartamentosAsync() {
            return base.Channel.GetDepartamentosAsync();
        }
        
        public ClienteDepartamentos.ServiceReference1.Departamentos[] GetDepartamentosAsynca() {
            return base.Channel.GetDepartamentosAsynca();
        }
        
        public System.Threading.Tasks.Task<ClienteDepartamentos.ServiceReference1.Departamentos[]> GetDepartamentosAsyncaAsync() {
            return base.Channel.GetDepartamentosAsyncaAsync();
        }
    }
}
