//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteTabla.ServicioTabla {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioTabla.ITabla")]
    public interface ITabla {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITabla/TablaMultiplicar", ReplyAction="http://tempuri.org/ITabla/TablaMultiplicarResponse")]
        int[] TablaMultiplicar(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITabla/TablaMultiplicar", ReplyAction="http://tempuri.org/ITabla/TablaMultiplicarResponse")]
        System.Threading.Tasks.Task<int[]> TablaMultiplicarAsync(int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITablaChannel : ClienteTabla.ServicioTabla.ITabla, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TablaClient : System.ServiceModel.ClientBase<ClienteTabla.ServicioTabla.ITabla>, ClienteTabla.ServicioTabla.ITabla {
        
        public TablaClient() {
        }
        
        public TablaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TablaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TablaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TablaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] TablaMultiplicar(int numero) {
            return base.Channel.TablaMultiplicar(numero);
        }
        
        public System.Threading.Tasks.Task<int[]> TablaMultiplicarAsync(int numero) {
            return base.Channel.TablaMultiplicarAsync(numero);
        }
    }
}
